#!/bin/sh

[ "$1" = "" ] && {
  echo "gogogo: Project required";
  exit;
}

SOURCE_PATH=~/go/src/
[

TMP_PROJECT_FOLDER=$SOURCE_PATH/gogogo_tmp
PROJECT_TO_GOGOGONIZE=$SOURCE_PATH/$1
OUTPUT_FOLDER=$(pwd)
AWK_SCRIPT=$(cat << EOM
{
    if ($1 == "%%assert") {
        {
            split($0,a,"%%assert");
            split(a[2], b, ";");
            print a[1]"if err != nil {\n"a[1]"\tl.Error(err.Error())\n"a[1]"\tv :="b[1]"\n"a[1]"\tl.Error(v)\n"a[1]"\treturn "b[2]"\n"a[1]"}";
        }
    } else {
        print $0;
    }
}
EOM)

cp $PROJECT_TO_GOGOGONIZE $TMP_PROJECT_FOLDER

for f in $TMP_PROJECT_FOLDER/*
do
  echo "Processing file "$f
  awk $AWK_SCRIPT 
done

[ "$2" = "build" ] && {
  go build gogogo_tmp;
  mv gogogo_tmp $1;
}

[ "$2" = "run" ] && go run gogogo_tmp;

rm -rf $TMP_PROJECT_FOLDER
