#!/bin/sh

[ "$1" = "" ] && {
  echo "gogogo: Project required";
  exit;
}

SOURCE_PATH=~/go/src
TMP_PROJECT_FOLDER=$SOURCE_PATH/gogogo_tmp
PROJECT_TO_GOGOGONIZE=$SOURCE_PATH/$1
OUTPUT_FOLDER=$(pwd)

cp -r $PROJECT_TO_GOGOGONIZE $TMP_PROJECT_FOLDER

for f in $TMP_PROJECT_FOLDER/*
do
  echo "Processing file "$f
  awk -f mymacros.awk $f
done

[ "$2" = "build" ] && {
  go build gogogo_tmp;
  mv gogogo_tmp $1;
}

[ "$2" = "run" ] && go run gogogo_tmp;

rm -rf $TMP_PROJECT_FOLDER
